export const Services = [
  {
    icon: "/icone-service.svg",
    service: "Investissement Publicité en ligne",
    bg: "bg-indigo-100",
    p1: "Publicité sur Google Ads",
    p2: "Campagne Facebook Ads",
    p3: "Boostez vos ventes sur Instagram",
    p4: "Visibilité sur Youtube",
  },
  {
    icon: "/icone-service.svg",
    service: "Conseil Marketing Stratégie",
    bg: "bg-green-100",
    p1: "Définir les leviers de croissance",
    p2: "Analyser les canaux de communication",
    p3: "Développer vos ventes web",
    p4: "Suivre votre développement digital",
  },
  {
    icon: "/icone-service.svg",
    service: "Formation Numérique",
    bg: "bg-red-100",
    p1: "Formez vos équipes en marketing digital",
    p2: "Expertise sur les réseaux sociaux",
    p3: "Analyse de la présence digitale",
    p4: "Recommandation stratégique",
  },
  {
    icon: "/icone-service.svg",
    service: "Contenus Marketing",
    bg: "bg-yellow-100",
    p1: "Vidéos & photos publicitaires",
    p2: "Contenus pour les réseaux sociaux & site web",
    p3: "Catalogues produits",
    p4: "Prises de vue aériennes - Drone",
  },
  {
    icon: "/icone-service-developpement-web.svg",
    service: "Développement Web",
    bg: "bg-sky-100",
    p1: "Création de site web & vitrine",
    p2: "Ventes en ligne via e-commerce",
    p3: "Développement d'application web",
    p4: "Outils informatique",
  },
];
